### ISSUE TITLE
打开就报错

### ISSUE THREAD

**Issue by jennins1** [wangdingfu/fu-api-doc-plugin#21]
【Fu Doc】执行动作失败
  
  java.lang.NullPointerException: Cannot invoke "com.wdf.fudoc.apidoc.pojo.desc.ObjectInfoDesc.setRootId(java.lang.Integer)" because "objectInfoDesc" is null
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.paddingRootId(FuDocDefaultParser.java:204)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.paddingRootId(FuDocDefaultParser.java:207)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:92)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.doParseDefaultObject(FuDocDefaultParser.java:122)
at com.wdf.fudoc.apidoc.parse.object.impl.FuDocDefaultParser.parse(FuDocDefaultParser.java:86)
at com.wdf.fudoc.apidoc.parse.ObjectParserExecutor.execute(ObjectParserExecutor.java:52)
at com.wdf.fudoc.apidoc.parse.FuDocClassParserImpl.requestParse(FuDocClassParserImpl.java:116)
at com.wdf.fudoc.apidoc.parse.FuDocClassParserImpl.parse(FuDocClassParserImpl.java:88)
at com.wdf.fudoc.util.GenFuDocUtils.buildClassInfoDesc(GenFuDocUtils.java:40)
at com.wdf.fudoc.util.GenFuDocUtils.gen(GenFuDocUtils.java:26)
at com.wdf.fudoc.apidoc.service.GenControllerFuDocServiceImpl.genFuDocContent(GenControllerFuDocServiceImpl.java:28)
at com.wdf.fudoc.apidoc.action.GenFuDocAction.execute(GenFuDocAction.java:49)
at com.wdf.fudoc.common.AbstractClassAction.actionPerformed(AbstractClassAction.java:113)
at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)
at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
at java.desktop/java.awt.Component.processEvent(Component.java:6422)
at java.desktop/java.awt.Container.processEvent(Container.java:2266)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by wangdingfu** [comment]
已经发布新版本了 正在等待JetBrains审核中 预计两天内会审核通过 到时候更新即可

**Comment by wangdingfu** [comment]
版本号是：xxx.1.8.4
